title: Incomplete Democracy: Mapping Protest as New Indicators of Political Sentiment
author: Wooseok Jang, Yeonjin Kim
description: Protest Timeline Visualization Project
baseurl: "/conflict_urbanism_sp2025_Woosek-Yeonjin"
