layout: post
date:   2025-05-05
image: "/template_site/images/csr_thumbnail.png"
title:  "Incomplete Democracy: Mapping Protest as New Indicators of Political Sentiment"
author: "Wooseok Jang, Yeonjin Kim"
