baseurl: "/conflict_urbanism_sp2025_Woosek-Yeonjin"
url: "https://yeonjin-kimm.github.io/conflict_urbanism_sp2025_Woosek-Yeonjin/"

title: "Conflict Urbanism 2025"
author: "Wooseok Jang, Yeonjin Kim"
externallink: "ljk33@columbia.edu"
description: "Student projects from the Spring 2025 Conflict Urbanism seminar."

theme: minima
plugins:
  - jekyll-feed
